version: "3.8"

services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 3000:3000
    # [figure out a way to map volume from this folder to container so changes you make to this folder will be visible from container immediately]

  # Not recommended > 

  # frontend-tests:
  #   image: vidly_frontend
  #   volumes: 
  #     - ./frontend:/app
  #   command: npm test

  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    volumes:
      - ./backend:/app
    # command: ./wait-for db:27017 && migrate-mongo up && npm start
    
    # alternatively >
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
